language: python
python:
    - 3.3
install:
    - "pip install --use-mirrors coveralls"
    - "pip install --use-mirrors tox"
    - "pip install --use-mirrors -r requirements.txt"
script:
    - "python setup.py test"
after_success:
    - coveralls
